### ISSUE TITLE
"getting started" button does not hide away

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#1044]
The button is quite large for some screen resolutions and there is no way to hide it.

**Comment by riknoll** [comment]
I believe this is fixed now that the button moves into the toolbar and disappears in mobile.

**Comment by pelikhan** [comment]
Still an issue in tablet mode on small screens that are at the edge of the résiliation breakpoint.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
