### ISSUE TITLE
When use the “search” box to find existing package, no results.

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#1573]
•	Navigate to https://pxt.microbit.org/beta  
•	Click “Add Package” 
•	Such as taping “radio” on search box
•	Press “Search”
![4](https://cloud.githubusercontent.com/assets/23497626/23652023/3a0c4868-02dc-11e7-8b31-36a5d212308c.PNG)

**Expect result** : 
The list should have ‘radio’ package.

**Actual result** :
No corresponding results.
![5](https://cloud.githubusercontent.com/assets/23497626/23652106/80cd554e-02dc-11e7-82d4-a38f0e530d84.PNG)

**Comment by pelikhan** [comment]
Search does not seem to match built-in packages.

**Comment by pelikhan** [comment]
Fixed.

**Comment by WendyFeng01** [comment]
This bug still repro. When I search the "radio", no corresponding results.
![capture](https://cloud.githubusercontent.com/assets/23497626/25609654/a260142e-2f52-11e7-80be-a83ce2bfecff.PNG)

**Comment by pelikhan** [comment]
If radio is already added to your project, it will not show up.
