### ISSUE TITLE
Right click the blocks, one prompting message will cover the other prompting message "Help".

### ISSUE THREAD

**Issue by WendyFeng01** [Microsoft/pxt#1765]
**Repro steps:**

- Navigate to https://pxt.microbit.org/beta 
- Click the "Basic" and right click "show number"
![help](https://cloud.githubusercontent.com/assets/23497626/24394903/9f794a1c-1352-11e7-8b63-33b16c0320e3.gif)

Expect result:
Two prompting message should show in one message,  or the first message should not cover the other message 
Actual result:
One prompting message will cover the message "Help"

**Comment by microsoftsam** [comment]
Blockly issue.

**Comment by microsoftsam** [comment]
Fixed by #2146

**Comment by WendyFeng01** [comment]
This bug still repro on build 16201.1002.170523-1730
**Repro browsers**: Edge, IE, Chrome and Firefox

![help](https://cloud.githubusercontent.com/assets/23497626/26478130/afee5b7a-41fc-11e7-8560-573aafa87f47.gif)

**Comment by microsoftsam** [comment]
Fixed in master

________________________________
