### ISSUE TITLE
Pin blocks differ by language

### ISSUE THREAD

**Issue by microbit-matt** [Microsoft/pxt#2342]
microbit.org-ticket: 2028

Hi PXT / MakeCode team 👋 ,

I'm here looking for some help as we've had a bug report from a user of http://makecode.microbit.org that they're unable to reproduce a program written in English using the Dutch language setting. It appears that the blocks in the Pin package for each language are different. User screenshots are included below:

- [English language version](https://user-images.githubusercontent.com/28565144/27486110-59eaf922-5827-11e7-8e4f-0564f9a32347.png)
- [Dutch language version](https://user-images.githubusercontent.com/28565144/27486145-7d5ff42a-5827-11e7-9515-71e97d98b7ad.png)

Here is a screenshot of the blocks for the two packages side by side:

![screenshot 2017-06-23 15 24 08](https://user-images.githubusercontent.com/28565144/27486313-128c81f8-5828-11e7-994c-4369f7758aaa.png)

The user supplied the following version information:

```
makecode.microbit.org version: 0.12.40
Microsoft MakeCode version: 0.12.94
C++ runtime version: v2.0.0-rc11
```

Many thanks in advance for your help 😄 

Matt

**Comment by microsoftsam** [comment]
Hey Matt, 

Thanks for getting in touch.
The issue here is that the Dutch translation has messed up the block inputs.
For example, the block text for analog set period pin is: 
```
analog set period|pin %pin|to (µs)%micros
```

The current translation for that block is: 
```
zet analoge periode|pin %pin|op (µs) % micros
```
where as it should be: 
```
zet analoge periode|pin %pin|op (µs) %micros
```

(Notice the whitespace between % and micros)

I can fix this issue now.

Our editor is localized by the community through crowd in, so if you're a Dutch speaker and you're interested in helping with the localization effort, or if you notice an issue and want to help fix it, go to https://crowdin.com/project/kindscript

**Comment by microsoftsam** [comment]
@pelikhan we should look into an automated way to catch these kind of simple issues in the translations: 
- space before parameter name
- translating the parameter name

**Comment by pelikhan** [comment]
We do have parameter validation in place and it should ignore ill formed strings. Needs to be investigated

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DavidWhaleMEF** [comment]
Any progress on this issue? Thanks!

**Comment by DavidWhaleMEF** [comment]
Any progress on this issue to report? Customer is waiting for some form of update on it, thanks!

**Comment by abchatra** [comment]
@microsoftsam is this issue addressed in beta?

**Comment by microsoftsam** [comment]
@pelikhan?

**Comment by microsoftsam** [comment]
This particular issue with the pin blocks has been fixed. 
@pelikhan mind looking it why the parameter validation didn't catch this issue in the first place?

**Comment by microbit-matt** [comment]
Hi @microsoftsam,

It looks like 3/4 of the cases listed in the original screenshot have been fixed. I can still see one block in the pin library with differences between English and Dutch. I've attached a screenshot below:

<img width="1440" alt="screenshot 2017-08-07 09 54 22" src="https://user-images.githubusercontent.com/28565144/29019596-e7c8b020-7b56-11e7-9c53-f53e9e9ec705.png">

Would it be possible to re-open this issue until that is fixed? Thanks for your work on this so far! 😄

**Comment by pelikhan** [comment]
@microbit-matt could you fix the translation in crowdin? This particular issue is that %variables should not be translated. We have added better detection for erroneous strings but they are not on deployed yet.

**Comment by microbit-matt** [comment]
@pelikhan I'm not a member of the project - if you can add me I can look at fixing it. I'm `microbit-matt` on CrowdIn.

**Comment by pelikhan** [comment]
Please open a translator request on https://crowdin.com/project/kindscript/ and I’ll take it from there.

**Comment by pelikhan** [comment]
I’ve fixed the issues, it may take a day to make it into the live web site.

From: Peli de Halleux
Sent: Tuesday, August 8, 2017 11:46 AM
To: 'Microsoft/pxt' <reply@reply.github.com>; Microsoft/pxt <pxt@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Microsoft/pxt] Pin blocks differ by language (#2342)

Please open a translator request on https://crowdin.com/project/kindscript/ and I’ll take it from there.

**Comment by microbit-matt** [comment]
Thanks for the fix @pelikhan 😄  I've just requested to join the project on CrowdIn anyway so that I can update the translations in the event that a user reports the same issue in future.
