### ISSUE TITLE
[Screen Reader-Project-Makecode Documentation] Screen Reader is not giving information about the category under which links are present like Games, Multiplayer Games.

### ISSUE THREAD

**Issue by v-mesala** [Microsoft/pxt#2802]
**User Experience:**
User who depends on screen reader may get Confuse if the information about the category under which links are present like Games, Multiplayer Games is not given.

**Test Environment:**
OS: RS2 Version 1703(OS Build 15063.2)
Platform: Edge.
Screen Reader : Narrator

**Repro Steps:-**
1. Navigate to https://makecode.microbit.org/projects
2. Navigate to projects in the left pane and select it.
3. Navigate through the page opened and verify the issue.

**Actual Result:-**
Screen Reader is not giving information about the category under which links are present like Games, Multiplayer Games.

**Expected Result:-**
Screen Reader should give information about the category under which links are present like Games, Multiplayer Games.

**Note:** 
This issue exists with Firefox also.

**MAS Reference -**
https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Please refer the Attachment:**
[MAS1.3.1_Screen Reader is not giving information under which links are present.zip](https://github.com/Microsoft/pxt/files/1248677/MAS1.3.1_Screen.Reader.is.not.giving.information.under.which.links.are.present.zip)

**Comment by veler** [comment]
Fix available on [https://makecode.microbit.org/](https://makecode.microbit.org/)

**Comment by v-mesala** [comment]
Verified on URL: https://makecode.microbit.org/projects and issue is not fixed now. Hence reactivating the bug.

**Comment by samelhusseini** [comment]
Hi @v-mesala, these are just normal headings and subheadings and not **category titles.** I've verified that the content on that page conforms to heading ranks (<h1> then <h2>, etc). 

I don't think there's any work on our part for this. 
Please verify and close. @v-mesala @v-amik.

**Comment by v-swasha** [comment]
Bug is verified on the URL: https://makecode.microbit.org/projects and issue is fixed as on navigating using heading more screen reader is reading the content information.
Hence closed the bug and please Add close tag as i dont have access to add tag.
